language: csharp  
sudo: required  
dist: trusty 

configuration:
- Release

env:  
  - CLI_VERSION=latest
addons:  
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
mono:  
  - 4.2.3

linux: &linux
   os: linux
   sudo: required
   language: python
   python: "3.6"
   services:
     - docker

osx: &osx
   os: osx
   language: generic

matrix:
   include:
      - <<: *linux
        env: CONAN_GCC_VERSIONS=5.4 CONAN_DOCKER_IMAGE=lasote/conangcc54

      - <<: *osx
        osx_image: xcode8.3
        env: CONAN_APPLE_CLANG_VERSIONS=8.1  

before_install:  
  - |
    if test "$TRAVIS_OS_NAME" == "osx"; then
      ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/;
      ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/;
    fi

install:
  - set -e

  - |
    if [[ "${UPDATE_DOCS}" != "true" ]]; then
      if [[ "${TRAVIS_OS_NAME}" != "linux" ]]; then
        brew update || brew update
        brew outdated pyenv || brew upgrade pyenv
        brew install pyenv-virtualenv
        brew install cmake || true
        if which pyenv > /dev/null; then
            eval "$(pyenv init -)"
            eval "$(pyenv virtualenv-init -)" 
        fi
        if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
          pyenv install 2.7.10
          pyenv virtualenv 2.7.10 conan
        else
          pyenv install 3.6.1
          pyenv virtualenv 3.6.1 conan
        fi
        pyenv rehash
        pyenv activate conan
      fi
    fi
  - sudo -H pip install conan_package_tools --upgrade
  - sudo -H pip install conan --upgrade
  - conan user
  - conan remote add bitprim_temp https://api.bintray.com/conan/bitprim/bitprim
  - wget https://raw.githubusercontent.com/dario-ramos/bitprim-cs/dev/conanfile.txt
  - conan install .
  - export DOTNET_INSTALL_DIR="$PWD/.dotnetcli"
  - curl -sSL https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.sh | bash /dev/stdin --version "$CLI_VERSION" --install-dir "$DOTNET_INSTALL_DIR"
  - export PATH="$DOTNET_INSTALL_DIR:$PATH"  
script:
  - chmod +x build.sh  
  - ./build.sh
