
language: csharp

matrix:
   include:
    - dotnet: 1.0.1
      mono: none
      dist: trusty
      env: DOTNETCORE=1  # optional, can be used to take different code paths in your script
      solution: bitprim-cs.sln
    - mono: latest
      solution: bitprim-cs.sln
