build: off

branches:
  only:
  - dev
  - /^v\d+\.\d+\.\d+$/
  - /^release-\d+\.\d+\.\d+$/
  - /^feature-ci-.+$/
  - /^feature_ci_.+$/

platform:
  - x64

configuration:
- Release

environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "32"
    NUGET_API_KEY:
      secure: v1FcTnqyvedsvmDN+hkritZIzgvbs19CsZ9CB1Lxdq6SLi4FEeMZC5eBRulPmN+2

    VS150COMNTOOLS: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\Tools\\"

    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          PUBLISH_TO_NUGET: "true"

assembly_info:
  patch: false

install:
  - "%PYTHON%/Scripts/pip.exe install conan --upgrade"

build_script:
  - SET PATH=%PATH%;%PYTHON%/Scripts/
  - powershell .\build.ps1

test: off
