build: false

configuration:
- Release

environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "32"
    NUGET_API_KEY:
      secure: QXiv4MV3IX8V/7hl+CGMAH9vcLaUJ12ZEk2ohcKiumfT0jS3AzfkJ13qES92E5Pt

    VS150COMNTOOLS: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\Tools\\"
    
    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          PUBLISH_TO_NUGET: false
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          PUBLISH_TO_NUGET: true

build_script:
  - SET PATH=%PATH%;%PYTHON%/Scripts/
  - dotnet build bitprim.sln /property:Platform=x64

install:
  - "%PYTHON%/Scripts/pip.exe install conan --upgrade"
  - icacls "%APPVEYOR_BUILD_FOLDER%"\bitprim.tests /grant Everyone:F
  - icacls "%APPVEYOR_BUILD_FOLDER%"\bitprim.tests\* /grant Everyone:F

test_script:
  - cd bitprim.tests
  - dotnet test /property:Platform=x64 -f netcoreapp2.0

after_build:
    - IF "%%PUBLISH_TO_NUGET%%"=="true" (
        del "%APPVEYOR_BUILD_FOLDER%"\bitprim\bin\x64\Release\*.nupkg
        powershell .\increment_version.ps1
        dotnet build "%APPVEYOR_BUILD_FOLDER%"\bitprim\bitprim.csproj /property:Platform=x64
        dotnet nuget push "%APPVEYOR_BUILD_FOLDER%"\bitprim\bin\x64\Release\*.nupkg -s https://www.nuget.org/api/v2/package -k %NUGET_API_KEY%
    )
